##################################################################################################
# Productpage service
##################################################################################################
apiVersion: v1
kind: Service
metadata:
  name: productpage-v1
  labels:
    app: productpage
    service: productpage
spec:
  type: LoadBalancer      #Para que añada una ip externa que será donde visualizaremos la aplicación 
  ports:
  - port: 9080
    name: http
    protocol: TCP
    targetPort: 9080
  selector:
    app: productpage
---
##################################################################################################
# Productpage deployment
##################################################################################################
apiVersion: apps/v1
kind: Deployment
metadata:
  name: productpage
  labels:
    app: productpage
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: productpage
      version: v1
  template:
    metadata:
      labels:
        app: productpage
        version: v1
    spec:
      containers:
      - name: productpage
        image: jorgerguezz/productpage:16   #16/productpage
        imagePullPolicy: IfNotPresent  
        ports:
        - containerPort: 9080
        securityContext:
          runAsUser: 1000
