version: '3'
services:
  productpage:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      GROUP_NUMBER: 16
    ports:
      - "9080:9080"
    container_name: "productpage-16"
    image: "productpage/16"

  details:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVICE_VERSION: v1
      ENABLE_EXTERNAL_BOOK_SERVICE: "true"
    ports:
      - "9081:9080"  # Cambiado el puerto local para evitar conflictos
    container_name: "details-16"
    image: "details/16"

  reviews:
    build:
      context: practica_creativa2/bookinfo/src/reviews/reviews-wlpcfg   # Usamos el que ya esta creado
      dockerfile: Dockerfile
    environment:
      SERVICE_VERSION: v3
      ENABLE_RATINGS: "true"
      STAR_COLOR: red
    ports:
      - "9082:9080"  # Cambiado el puerto local para evitar conflictos
    container_name: "reviews-16"
    image: "reviews/16"

  ratings:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      SERVICE_VERSION: v1
    ports:
      - "9083:9080"  # Cambiado el puerto local para evitar conflictos
    container_name: "ratings-16"
    image: "ratings/16"
